name: Publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    # prevents this action from running on forks
    if: github.repository == 'insco-inc/shasum'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set node
        uses: actions/setup-node@v5
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          package-manager-cache: false

      - name: Install Dependencies
        run: |
          npm i -g npm@^11.5.2
          npm i -g corepack
          corepack enable
          pnpm install

      - name: Publish
        run: pnpm publish --publish-branch main --provenance --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
